name = "GeneralizedSP2"
uuid = "5310a9d4-a676-4946-a68d-8e46a0f50a7f"
authors = ["Kipton Barros <kbarros@gmail.com>", "singularitti <singularitti@outlook.com>"]
version = "1.0.0-DEV"

[deps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ExponentialUtilities = "d4d017d3-3776-5f7e-afef-a10c40355c18"
GershgorinDiscs = "1acd937f-ba38-4cfb-ac8e-9b470edff748"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Enzyme = "0.13"
ExponentialUtilities = "1.26.1"
GershgorinDiscs = "0.1.0"
LinearAlgebra = "1.6"
LsqFit = "0.15"
NPZ = "0.4"
SparseArrays = "1.6"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
