name = "GeneralizedSP2"
uuid = "5310a9d4-a676-4946-a68d-8e46a0f50a7f"
authors = ["Kipton Barros <kbarros@gmail.com>", "singularitti <singularitti@outlook.com>"]
version = "1.0.0-DEV"

[deps]
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
LeastSquaresOptim = "0.8.5"
LinearAlgebra = "1.11.0"
LsqFit = "0.15.0"
SparseArrays = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
